### ISSUE TITLE
why are the llvm static libraries deleted?

### ISSUE THREAD

**Issue by barcharcraz** [flathub/org.freedesktop.Sdk.Extension.llvm12#2]
the libLLVM static libraries are deleted by the cleanup section in the build script, this breaks the LLVM cmake configuration files installed. If you don't want the static libraries for some reason why not just not build them, instead of building them and then deleting them. This has the additional advantage of not breaking other stuff installed by the build, unless there's a bug in LLVM's build system.

**Comment by Erick555** [comment]
The static libs are deleted because of additional size reason which affects both the extension and every flatpak app that may use them. Using libLLVM shared library is strongly encouraged instead. I don't know of an easy way to disable building of static libraries so if you do then please open PR.

**Comment by Erick555** [comment]
https://github.com/flathub/org.freedesktop.Sdk.Extension.llvm12/commit/02d3dfd76fcc95cc4b941571029170b6589abdde stops installing static libs, remove static libs headers and expose more shared libs. I hope this solves this issue.
