### ISSUE TITLE
publish 21.08beta version to flathub-beta

### ISSUE THREAD

**Issue by abderrahim** [flathub/org.freedesktop.Sdk.Extension.llvm12#4]
freedeskop-sdk 21.08beta has been released, and it has dropped llvm. This means that now this extension is essential to those relying on llvm.

Asking on matrix, the way to do this is to create a branch named `beta` and change the branch name in the manifest, like https://github.com/flathub/org.freedesktop.Sdk.Extension.rust-stable/commits/beta

**Comment by Erick555** [comment]
Fixed by https://github.com/flathub/org.freedesktop.Sdk.Extension.llvm12/pull/5 and https://github.com/flathub/org.freedesktop.Sdk.Extension.llvm12/pull/7
